### ISSUE TITLE
When running magpie.sh, getting ImportError: cannot import name 'disable_created_metrics' from 'prometheus_client'

### ISSUE THREAD

**Issue by cyberkoolman** [magpie-align/magpie#12]
After successfully run demo.ipynb for the first run, then trying to run scripts/magpie.sh, getting an error:

![image](https://github.com/magpie-align/magpie/assets/5167152/38f640e1-cfbf-4fb9-84d4-dc97d9f4dac2)

**Comment by fly-dust** [comment]
Hi!
Seems that it is an issue from [vllm](https://github.com/vllm-project/vllm). What is your vllm version? Can you also check if `prometheus_client >= 0.18.0` in your environment?

**Comment by fly-dust** [comment]
demo.ipynb uses Huggingface transformers as the backend engine, and the scripts use vllm for faster batch inference.

**Comment by cyberkoolman** [comment]
vllm version is 0.4.2 and prometheus_client is 0.14.1.  I also see there's prometheus-client that is version 0.20.0.  Which one of these does it use?

**Comment by fly-dust** [comment]
My env uses 0.20.0, it works great

**Comment by cyberkoolman** [comment]
I upgraded vllm to 0.5.1, still the same error, anything else I should try?  Again, I see prometheus-client == 0.20.0, and prometheus_client == 0.14.1.

**Comment by fly-dust** [comment]
Can you try to uninstall `prometheus_client == 0.14.1`?

**Comment by fly-dust** [comment]
Since no response has been received, I will close this issue.
