### ISSUE TITLE
关于magpie微调的一个疑惑

### ISSUE THREAD

**Issue by rangehow** [magpie-align/magpie#14]
我试了一下，在llama3-8b上使用magpie-pro-300k训练，在benchmark上差llama3-8b-it差很多，不是一星半点的差，在10个benchmark，mmlu gsm8k humaneval 等等上，能掉十几分到几十分不等，比如gsm8k，official instruct version 79.6 while magpie tuned version 40+ even worse than base model 55+ ... ... 

然后我快速翻看了一下论文，发现只做了类似alpacaeval这种大模型评测。是因为你们在实验里也发现了这个现象吗？

**Comment by fly-dust** [comment]
llama3-8b-instruct很神奇，一点没有alignment tax, 这些benchmark比base还要高就很诡异（怀疑应该是针对性训练过了）
我们附录里有其他benchmark的结果，和用其他SFT data训练的model是comparable的，应该大家都吃了一波alignment tax，很正常～
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/436776c0-4a19-4f52-970f-2ee60b08d3d4">
另外我们新train了一个checkpoint，[Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2](https://huggingface.co/Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2)，通过magpie合成了150K的reasoning dataset并且和300K的数据一起做SFT，GSM8K是63，比之前好多了
还有GSM8K用于Instruct Model，很有会有没有匹配上答案的问题。可以用我们刚发布的的[ZeroEval](https://github.com/yuchenlin/ZeroEval)来评测

**Comment by rangehow** [comment]
感谢您及时的回复，还想请问一个题外话，[ZeroEval](https://github.com/yuchenlin/ZeroEval) 在解决答案匹配上有什么优势吗，现在主流是shot引导+正则抽取，确实有抽错的情况，你们设计的框架是怎么解决这个问题的呢~

**Comment by fly-dust** [comment]
[Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2](https://huggingface.co/Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2)的downstream benchmark分数：
|                         Task                         |Version|    Metric    |Value |   |Stderr|
|------------------------------------------------------|------:|--------------|-----:|---|-----:|
|all                                                   |       |acc           |0.6556|±  |0.0323|
|                                                      |       |acc_norm      |0.7018|±  |0.0091|
|                                                      |       |truthfulqa_mc1|0.3354|±  |0.0165|
|                                                      |       |truthfulqa_mc2|0.5081|±  |0.0152|
|                                                      |       |qem           |0.6308|±  |0.0133|
|leaderboard:arc:challenge:25                          |      0|acc           |0.5666|±  |0.0145|
|                                                      |       |acc_norm      |0.5964|±  |0.0143|
|leaderboard:gsm8k:5                                   |      0|qem           |0.6308|±  |0.0133|
|leaderboard:hellaswag:10                              |      0|acc           |0.6147|±  |0.0049|
|                                                      |       |acc_norm      |0.8072|±  |0.0039|
|leaderboard:mmlu:_average:5                           |       |acc           |0.6565|±  |0.0335|
|leaderboard:mmlu:abstract_algebra:5                   |      0|acc           |0.3600|±  |0.0482|
|leaderboard:mmlu:anatomy:5                            |      0|acc           |0.6370|±  |0.0415|
|leaderboard:mmlu:astronomy:5                          |      0|acc           |0.7105|±  |0.0369|
|leaderboard:mmlu:business_ethics:5                    |      0|acc           |0.6300|±  |0.0485|
|leaderboard:mmlu:clinical_knowledge:5                 |      0|acc           |0.7170|±  |0.0277|
|leaderboard:mmlu:college_biology:5                    |      0|acc           |0.7708|±  |0.0351|
|leaderboard:mmlu:college_chemistry:5                  |      0|acc           |0.4900|±  |0.0502|
|leaderboard:mmlu:college_computer_science:5           |      0|acc           |0.5400|±  |0.0501|
|leaderboard:mmlu:college_mathematics:5                |      0|acc           |0.3600|±  |0.0482|
|leaderboard:mmlu:college_medicine:5                   |      0|acc           |0.6301|±  |0.0368|
|leaderboard:mmlu:college_physics:5                    |      0|acc           |0.4412|±  |0.0494|
|leaderboard:mmlu:computer_security:5                  |      0|acc           |0.7700|±  |0.0423|
|leaderboard:mmlu:conceptual_physics:5                 |      0|acc           |0.5404|±  |0.0326|
|leaderboard:mmlu:econometrics:5                       |      0|acc           |0.5175|±  |0.0470|
|leaderboard:mmlu:electrical_engineering:5             |      0|acc           |0.6621|±  |0.0394|
|leaderboard:mmlu:elementary_mathematics:5             |      0|acc           |0.4339|±  |0.0255|
|leaderboard:mmlu:formal_logic:5                       |      0|acc           |0.5079|±  |0.0447|
|leaderboard:mmlu:global_facts:5                       |      0|acc           |0.3900|±  |0.0490|
|leaderboard:mmlu:high_school_biology:5                |      0|acc           |0.7677|±  |0.0240|
|leaderboard:mmlu:high_school_chemistry:5              |      0|acc           |0.5025|±  |0.0352|
|leaderboard:mmlu:high_school_computer_science:5       |      0|acc           |0.7000|±  |0.0461|
|leaderboard:mmlu:high_school_european_history:5       |      0|acc           |0.7576|±  |0.0335|
|leaderboard:mmlu:high_school_geography:5              |      0|acc           |0.8182|±  |0.0275|
|leaderboard:mmlu:high_school_government_and_politics:5|      0|acc           |0.9016|±  |0.0215|
|leaderboard:mmlu:high_school_macroeconomics:5         |      0|acc           |0.6231|±  |0.0246|
|leaderboard:mmlu:high_school_mathematics:5            |      0|acc           |0.3815|±  |0.0296|
|leaderboard:mmlu:high_school_microeconomics:5         |      0|acc           |0.6891|±  |0.0301|
|leaderboard:mmlu:high_school_physics:5                |      0|acc           |0.4437|±  |0.0406|
|leaderboard:mmlu:high_school_psychology:5             |      0|acc           |0.8239|±  |0.0163|
|leaderboard:mmlu:high_school_statistics:5             |      0|acc           |0.5185|±  |0.0341|
|leaderboard:mmlu:high_school_us_history:5             |      0|acc           |0.8382|±  |0.0258|
|leaderboard:mmlu:high_school_world_history:5          |      0|acc           |0.8186|±  |0.0251|
|leaderboard:mmlu:human_aging:5                        |      0|acc           |0.7130|±  |0.0304|
|leaderboard:mmlu:human_sexuality:5                    |      0|acc           |0.7481|±  |0.0381|
|leaderboard:mmlu:international_law:5                  |      0|acc           |0.8430|±  |0.0332|
|leaderboard:mmlu:jurisprudence:5                      |      0|acc           |0.7500|±  |0.0419|
|leaderboard:mmlu:logical_fallacies:5                  |      0|acc           |0.7362|±  |0.0346|
|leaderboard:mmlu:machine_learning:5                   |      0|acc           |0.4911|±  |0.0475|
|leaderboard:mmlu:management:5                         |      0|acc           |0.8447|±  |0.0359|
|leaderboard:mmlu:marketing:5                          |      0|acc           |0.8889|±  |0.0206|
|leaderboard:mmlu:medical_genetics:5                   |      0|acc           |0.8100|±  |0.0394|
|leaderboard:mmlu:miscellaneous:5                      |      0|acc           |0.8199|±  |0.0137|
|leaderboard:mmlu:moral_disputes:5                     |      0|acc           |0.7168|±  |0.0243|
|leaderboard:mmlu:moral_scenarios:5                    |      0|acc           |0.4223|±  |0.0165|
|leaderboard:mmlu:nutrition:5                          |      0|acc           |0.7484|±  |0.0248|
|leaderboard:mmlu:philosophy:5                         |      0|acc           |0.6752|±  |0.0266|
|leaderboard:mmlu:prehistory:5                         |      0|acc           |0.7315|±  |0.0247|
|leaderboard:mmlu:professional_accounting:5            |      0|acc           |0.4574|±  |0.0297|
|leaderboard:mmlu:professional_law:5                   |      0|acc           |0.4498|±  |0.0127|
|leaderboard:mmlu:professional_medicine:5              |      0|acc           |0.6875|±  |0.0282|
|leaderboard:mmlu:professional_psychology:5            |      0|acc           |0.6928|±  |0.0187|
|leaderboard:mmlu:public_relations:5                   |      0|acc           |0.6909|±  |0.0443|
|leaderboard:mmlu:security_studies:5                   |      0|acc           |0.7510|±  |0.0277|
|leaderboard:mmlu:sociology:5                          |      0|acc           |0.8607|±  |0.0245|
|leaderboard:mmlu:us_foreign_policy:5                  |      0|acc           |0.8500|±  |0.0359|
|leaderboard:mmlu:virology:5                           |      0|acc           |0.5120|±  |0.0389|
|leaderboard:mmlu:world_religions:5                    |      0|acc           |0.8363|±  |0.0284|
|leaderboard:truthfulqa:mc:0                           |      0|truthfulqa_mc1|0.3354|±  |0.0165|
|                                                      |       |truthfulqa_mc2|0.5081|±  |0.0152|
|leaderboard:winogrande:5                              |      0|acc           |0.7324|±  |0.0124|

另外方便问一下“在10个benchmark”是哪10个吗，我们这边也测一下

**Comment by fly-dust** [comment]
> 感谢您及时的回复，还想请问一个题外话，[ZeroEval](https://github.com/yuchenlin/ZeroEval) 在解决答案匹配上有什么优势吗，现在主流是shot引导+正则抽取，确实有抽错的情况，你们设计的框架是怎么解决这个问题的呢~

我们评测Zero-shot+强制Json输出,直接用解析Json就行。详见[这个tweet](https://x.com/billyuchenlin/status/1814037110577578377?s=46&t=rJeUt-UgmKMW8HFaMIUH9w)

**Comment by rangehow** [comment]
> 另外方便问一下“在10个benchmark”是哪10个吗，我们这边也测一下

btw 我再看了一下发现我记错了，gsm8k（8shot+cot）是20多。 我用8x H800，bsz 512训的，3个epoch，学习率那些都没调过，就hf的默认设置
truthfulqa_mc2 52.79390081174613
bbh_cot_few_shot 36.39993856550453
arc_c 41.89419795221843
agi_eval 29.88630865989357
sciq 93.5
winogrande 69.21862667719021
![ac113c201c7e25ea71db0c9eb6d4c28](https://github.com/user-attachments/assets/980fed82-546a-4162-ab31-76fbac2abfe3)

**Comment by fly-dust** [comment]
好滴thanks！ 我明天再研究研究这些benchmark!

**Comment by fly-dust** [comment]
> btw 我再看了一下发现我记错了，gsm8k（8shot+cot）是20多。 我用8x H800，bsz 512训的，3个epoch，学习率那些都没调过，就hf的默认设置

啊～或许可以参考一下[我们的超参](https://huggingface.co/Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2#framework-versions)，划到最下面展开就能看见配置文件了。感觉3个epoch可能有点过拟合了（不过只是猜测lol

**Comment by rangehow** [comment]
> > btw 我再看了一下发现我记错了，gsm8k（8shot+cot）是20多。 我用8x H800，bsz 512训的，3个epoch，学习率那些都没调过，就hf的默认设置
> 
> 啊～或许可以参考一下[我们的超参](https://huggingface.co/Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.2#framework-versions)，划到最下面展开就能看见配置文件了。感觉3个epoch可能有点过拟合了（不过只是猜测lol

好的，我现在训一组试试 : )

**Comment by huliang2016** [comment]
@rangehow hi, any update on this?

**Comment by rangehow** [comment]
@huliang2016 没有诶，当时挂的那组出了点问题崩溃了，因为赶due我就先放弃magpie了，以后有机会再尝试一下这个吧
