### ISSUE TITLE
Question About Using API version 

### ISSUE THREAD

**Issue by DylanDDeng** [magpie-align/magpie#15]
Hi, I read your paper and your finding is really amazing and interesting. I try it using ollama with qwen2-7B-instruct and it really works. The diversity of the data is really nice. However, when I try this on the siliconflow which is a platform to provide some larger models like Qwen2-72B-Instruct. The model will only generate very official response like "hello what can I do for you? " . 

I don't know why there exists huge differences of the data.  Are something wrong for what I do? 

Thanks for your work!

**Comment by fly-dust** [comment]
I guess the reason is that API service providers will add a conversation template for every query. That's why we need to generate instructions locally 😂.

**Comment by DylanDDeng** [comment]
Thanks for you explanation! That makes sense!

**Comment by fly-dust** [comment]
Let me know if you have further questions! I will close this issue for now.
