### ISSUE TITLE
How can I generate RM scores for Qwen2 model's data, Not the Llama3-8b-instruct?

### ISSUE THREAD

**Issue by FlyCarrot** [magpie-align/magpie#19]
When I switch to a different model for data generation, should I prepare a corresponding RM model as a baseline for RM score generation?
For example, 'sfairXC/FsfairX-LLaMA3-RM-v0.1' for llama3 model.
Maybe I use Qwen2 model, I don't find a good RM model based on Qwen2.
Did you train a model by yourself?
Or, could you recommend a list of RM models that would be suitable for other models?
Thanks

**Comment by fly-dust** [comment]
Hi,
You don't have to switch RMs. The choice of RM is independent of dataset generation; it simply provides a judge score. You can still use sfairXC/FsfairX-LLaMA3-RM-v0.1 to judge Qwen's output.
