### ISSUE TITLE
More details about controling LLMs to generate instructions

### ISSUE THREAD

**Issue by DeyangKong** [magpie-align/magpie#2]
Hello, can you provide more information about the **Instruction Generation Step** in the paper? Such as more prompts (since there is only a prompt related to math in fig12) and more detailed steps about getting the pre-query template (Other birds collect twigs for their nests. Magpies acquire jewels for theirs) from texts?
I would appreciate it if you could help me.

**Comment by fly-dust** [comment]
Hi,

Thank you for your message. We will add more examples in the codebase regarding different tasks. For the pre-query template, I think there is some misunderstanding~ You can refer to [configs/model_configs.json](https://github.com/magpie-align/magpie/blob/main/configs/model_configs.json) to see what typical pre-query templates look like. For example, the pre-query template for Llama-3 series is: <|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n. Please let us know if you have any further questions!
