### ISSUE TITLE
Can I extend 3rd, 4th turns using pre-generated magpie-mt dataset?

### ISSUE THREAD

**Issue by hyunwoongko** [magpie-align/magpie#21]
Using https://huggingface.co/datasets/Magpie-Align/Magpie-Llama-3.1-Pro-MT-500K-Filtered, Can I extend it to 3rd, 4th, ... turns? Thanks.

**Comment by fly-dust** [comment]
Yes, you can. Simply use [exp/gen_mt.py](https://github.com/magpie-align/magpie/blob/main/exp/gen_mt.py) and set `num_turns` to 3 or 4.
