### ISSUE TITLE
qwen2-math 有计划支持吗？

### ISSUE THREAD

**Issue by yucheng-zeng** [magpie-align/magpie#22]
我用 "pre_query_template": "<|im_start|>user\n" 对qwen2-math系列模型进行测试， 貌似结果不如预期。请问有什么方法吗？

**Comment by fly-dust** [comment]
Please check the newest commit and scripts/magpie-qwen2-math-7b.sh. 
Simply enabling the system prompt can solve this~

I can get something like this:
```
[
  {
    "id": 0,
    "pre_query_template": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n",
    "instruction": "Factor the trinomial 2x^2 + 5x + 3.",
    "response": null,
    "created": 1724114541,
    "gen_input_configs": {
      "temperature": 1.0,
      "top_p": 1.0,
      "input_generator": "Qwen/Qwen2-Math-7B-Instruct",
      "seed": null
    },
    "gen_response_configs": null
  },
  {
    "id": 1,
    "pre_query_template": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n",
    "instruction": "A rectangle with length 12 units and width 8 units is scaled by a factor of 2 to form a new rectangle. Determine the dimensions of the new rectangle and calculate its area. Compare the area of the new rectangle to the area of the original rectangle.",
    "response": null,
    "created": 1724114541,
    "gen_input_configs": {
      "temperature": 1.0,
      "top_p": 1.0,
      "input_generator": "Qwen/Qwen2-Math-7B-Instruct",
      "seed": null
    },
    "gen_response_configs": null
  },
  {
    "id": 2,
    "pre_query_template": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n",
    "instruction": "Find the area and perimeter of a rectangle with length 26 cm and width 14 cm.",
    "response": null,
    "created": 1724114541,
    "gen_input_configs": {
      "temperature": 1.0,
      "top_p": 1.0,
      "input_generator": "Qwen/Qwen2-Math-7B-Instruct",
      "seed": null
    },
    "gen_response_configs": null
  },
```

**Comment by yucheng-zeng** [comment]
感谢你的回复！
我又对qwen2-math系列模型做了测试，现在能正常输出指令。
关键点是 temperature 不能设置成 1，否则会有概率输出错误指令

> Please check the newest commit and scripts/magpie-qwen2-math-7b.sh. Simply enabling the system prompt can solve this~
> 
> I can get something like this:
> 
> ```
> [
>   {
>     "id": 0,
>     "pre_query_template": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n",
>     "instruction": "Factor the trinomial 2x^2 + 5x + 3.",
>     "response": null,
>     "created": 1724114541,
>     "gen_input_configs": {
>       "temperature": 1.0,
>       "top_p": 1.0,
>       "input_generator": "Qwen/Qwen2-Math-7B-Instruct",
>       "seed": null
>     },
>     "gen_response_configs": null
>   },
>   {
>     "id": 1,
>     "pre_query_template": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n",
>     "instruction": "A rectangle with length 12 units and width 8 units is scaled by a factor of 2 to form a new rectangle. Determine the dimensions of the new rectangle and calculate its area. Compare the area of the new rectangle to the area of the original rectangle.",
>     "response": null,
>     "created": 1724114541,
>     "gen_input_configs": {
>       "temperature": 1.0,
>       "top_p": 1.0,
>       "input_generator": "Qwen/Qwen2-Math-7B-Instruct",
>       "seed": null
>     },
>     "gen_response_configs": null
>   },
>   {
>     "id": 2,
>     "pre_query_template": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n",
>     "instruction": "Find the area and perimeter of a rectangle with length 26 cm and width 14 cm.",
>     "response": null,
>     "created": 1724114541,
>     "gen_input_configs": {
>       "temperature": 1.0,
>       "top_p": 1.0,
>       "input_generator": "Qwen/Qwen2-Math-7B-Instruct",
>       "seed": null
>     },
>     "gen_response_configs": null
>   },
> ```

**Comment by fly-dust** [comment]
好的，能用就行!
