### ISSUE TITLE
KeyError: 'uuid' during filtering

### ISSUE THREAD

**Issue by rickyang1114** [magpie-align/magpie#24]
Dear authors,

Thanks for your excellent work!

While attempting to execute `filtered_dataset = dataset['train'].filter(high_quality_filter)`, I encountered a `KeyError: 'uuid'`. Upon inspecting the code in [exp/gen_dis.py](https://github.com/magpie-align/magpie/blob/main/exp/gen_dis.py), it appears that the `uuid` value is not assigned. Could this be an oversight, or am I misunderstanding something?

**Comment by fly-dust** [comment]
Thank you point it out! My bad!

When fixing #20, I forgot to change `uuid` key too... It's now fixed!
