### ISSUE TITLE
how to exstract qwen72B chinese instruction?

### ISSUE THREAD

**Issue by moseshu** [magpie-align/magpie#3]
how to exstract qwen72B-instruct chinese instruction?

**Comment by fly-dust** [comment]
Hi, you can now use unitag.sh to mark Chinese instructions. You can also check the extracted Qwen2 data [here](https://huggingface.co/datasets/Magpie-Align/Magpie-Qwen2-Pro-1M-v0.1), where nearly 30% of the dataset is Chinese.
